import json
import pandas as pd
import plotly.express as px
import os
import webbrowser

# --- CONFIGURATION ---
# Point this to the JSON file generated by your main script
JSON_FILE = r"tsne_results\tsne_yolo11n-cls_model_model_10_linear.json"

def main():
    if not os.path.exists(JSON_FILE):
        print(f"Error: File not found: {JSON_FILE}")
        return

    print(f"Loading data from {JSON_FILE}...")
    with open(JSON_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    df = pd.DataFrame(data)
    print(f"Loaded {len(df)} points.")

    # --- AUTO-DETECT DIMENSIONS ---
    if 'z' in df.columns:
        print("Detected 3D data. Generating 3D Cube...")
        fig = px.scatter_3d(
            df, 
            x='x', 
            y='y', 
            z='z',
            color='class',
            hover_data=['filename'],
            title=f"3D Analysis: {os.path.basename(JSON_FILE)}",
            template="plotly_dark",
            width=1500, 
            height=900
        )
        # 3D points usually need to be smaller to see inside the cloud
        fig.update_traces(marker=dict(size=4, opacity=0.8))
        
    else:
        print("Detected 2D data. Generating Scatter Plot...")
        fig = px.scatter(
            df, 
            x='x', 
            y='y', 
            color='class',
            hover_data=['filename'],
            title=f"2D Analysis: {os.path.basename(JSON_FILE)}",
            template="plotly_dark",
            width=1500, 
            height=900,
            render_mode='webgl' # Optimization for 2D
        )
        fig.update_traces(marker=dict(size=6, opacity=0.8))

    # Save to HTML
    output_html = JSON_FILE.replace(".json", ".html")
    print(f"Saving to {output_html}...")
    fig.write_html(output_html)
    
    print("SUCCESS! Opening browser...")
    webbrowser.open(os.path.abspath(output_html))

if __name__ == "__main__":
    main()