import json
import pandas as pd
import plotly.express as px
import os

# --- CONFIGURATION ---
# Point this to the JSON file generated by your main script
JSON_FILE = r"tsne_results\file.json"

def main():
    if not os.path.exists(JSON_FILE):
        print(f"Error: File not found: {JSON_FILE}")
        return

    print(f"Loading data from {JSON_FILE}...")
    with open(JSON_FILE, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Convert to Pandas DataFrame for easier plotting
    df = pd.DataFrame(data)
    
    print(f"Plotting {len(df)} points...")

    # Create Interactive Scatter Plot
    fig = px.scatter(
        df, 
        x='x', 
        y='y', 
        color='class',                # Color points by class name
        hover_data=['filename', 'path'], # Show filename when hovering
        title=f"t-SNE Visualization: {os.path.basename(JSON_FILE)}",
        template="plotly_dark",       # Dark theme looks cool
        width=1500, 
        height=900,
        render_mode='webgl'           # CRITICAL: Makes it fast for 100k+ points
    )

    # Improve marker style
    fig.update_traces(marker=dict(size=5, opacity=0.8))

    # Save to HTML
    output_html = JSON_FILE.replace(".json", ".html")
    fig.write_html(output_html)
    
    print(f"SUCCESS! Open this file in your browser:\n{os.path.abspath(output_html)}")

    # Optional: Automatically open in browser
    import webbrowser
    webbrowser.open(os.path.abspath(output_html))

if __name__ == "__main__":
    main()